name: Dergons
main: no.runsafe.dergons.Dergons
version: 1.0.@BUILD@
author: Kruithne
description: Dergons!
commands:
  purgedergons:
    description: Purge all dergons from the world
  spawndergon:
    description: Spawn a dergon